### ISSUE TITLE
stackoverflow的链接已失效

### ISSUE THREAD

**Issue by palexu** [fsaimon/aria2.conf#1]
如题

**Comment by fsaimon** [comment]
被删除了😅
```
deleted by Community♦ Jun 24 '17 at 2:59 (RemoveAbandonedQuestions)
This question was automatically deleted. Please see the help center for more information.
```
不过，在 archive.org 上找到了存档，想看的话：
https://web.archive.org/web/20160902124010/https://stackoverflow.com/questions/37990530/use-launch-daemon-spawn-a-screen-session-run-aria2-rpc

然后我现在换 tmux 了，似乎没有这样的问题，基于 tmux 的 plist 已经提交了。
